"""Add horarios_funcionamento table and estudio relationship

Revision ID: ea9aa9b1eddd
Revises: 07505766e5c3
Create Date: 2025-11-19 14:49:44.547452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea9aa9b1eddd'
down_revision: Union[str, None] = '07505766e5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios_funcionamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudio_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=15), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('admins', 'tipo_admin',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.add_column('agendamentos', sa.Column('presenca', sa.Enum('presente', 'ausente', 'indefinido', name='presenca'), nullable=True))
    op.drop_constraint('agendamentos_ibfk_3', 'agendamentos', type_='foreignkey')
    op.drop_column('agendamentos', 'professor_id')
    op.drop_column('agendamentos', 'minha_presenca')
    op.drop_column('agendamentos', 'data_hora')
    op.alter_column('agendas', 'bloqueado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agendas', 'bloqueado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.add_column('agendamentos', sa.Column('data_hora', mysql.DATETIME(), nullable=False))
    op.add_column('agendamentos', sa.Column('minha_presenca', mysql.ENUM('presente', 'ausente', 'indefinido'), nullable=False))
    op.add_column('agendamentos', sa.Column('professor_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('agendamentos_ibfk_3', 'agendamentos', 'professores', ['professor_id'], ['id'])
    op.drop_column('agendamentos', 'presenca')
    op.alter_column('admins', 'tipo_admin',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_table('horarios_funcionamento')
    # ### end Alembic commands ###
